### ISSUE TITLE
Add HTML Export

### ISSUE THREAD

**Issue by SinclairC** [FeedTheCube/CogDoc#16]
Create an export function to generate a page that displays all required information about a report, or alternatively a function to output content in a form that can be fed to an existing page.

Questions:

1. Do you prefer for it to generate an HTML file or would you rather have it send JSON to a premade HTML page through an AJAX request? The former may mean it's easier to customize output based on what is needed for that specific page and also easier to get multiple reports at once, while the latter will be faster to run and easier to put together.

**Comment by hyndgrinder** [comment]
So, I forsee a number of states of user consumption, here are 3 that come to mind:
1) user is actively documenting a report, wants some sort of output to preserve.
2) user is looking through all of the collected data, perhaps to find reports, query, calculations which don't conform to a company standard
3) user is looking through all of the collected data trying to find objects they can copy from a pre-existing report into their report.

### 1)
This will ouput an actual file with a pretty and flattened display of a particular report or it's objects.  Perhaps it can iterate many reports, perhaps it can document less than a whole report, but the output will be 1 file (or if necessary a set of files) per report.  This role is about documenting the code in the Cognos solution.

### 2) 
In this role, the user is setting up to having a meeting with their subordinate developers, and correct some behaviors in a mentoring kind of way.  But there needs to be some sort of UI allowing them to query, select, and display the pool of objects so they can focus on the items of concern.  i.e. I still the user interacting with an interactive webpage, not a command line to produce this list.

### 3)
For this scenario, similar to 2, the user is navigating all the known reports and their objects.  But once found, they want to select particular objects and be able to copy their elements to their clipboard.  This allows them to paste into a new report they are building.  The simplest form of this I can imagine is to just `toString(element) ` and display on screen for the user to highlight/copy.

**Comment by SinclairC** [comment]
For part 1, see [htmlExport](https://github.com/FeedTheCube/CogDoc/tree/htmlExport) branch, which is currently very barebones and might need some tweaking even at this stage. Let me know if you have any thoughts on it.

The same thing could potentially work for parts 2 and 3, but would require some extra (pretty simple) JavaScript.
